apiVersion: v1
kind: Pod
metadata:
  name: candy-service
spec:
  containers:
  - name: candy-service
    image: linuxacademycontent/candy-service:2
    livenessProbe: #probe utilized to validate unhealthy state
      httpGet:
        path: /healthz
        port: 8081
      #initialDelaySeconds: 15 #optional settings
      #timeoutSeconds: 1 #optional settings
      #periodSeconds: 10 #optional settings
    readinessProbe: #probe utilized to make sure the pod is fully available after startup before servicing traffic
      httpGet:
        path: /
        port: 80